name: unit testing

on:
  push:
    branches:
      - main

jobs:
  test_cases_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install required library
        run: pip install -r requirements.txt

      - name: execute test cases
        run: pytest --cov=calc --cov-report=term



  

